---

- name: to run a redis server 
  hosts: webhost
  become: true
  tasks:
    - name: install epel-release
      yum: 
        name: epel-release
        state: latest
          
    - name: install redis
      yum: 
         name: redis
         state: latest
           
    - name: run redis
      service: 
          name: redis
          state: started
          enabled: yes
            
